### ISSUE TITLE
API docs and examples?

### ISSUE THREAD

**Issue by adamfeuer** [YosaiProject/yosai#15]
Hi,

Are there examples or API docs (for instance on Read The Docs)? I looked but couldn't find any..

I'm working on extending a home-grown RBAC with finer-grained permissions and audit log, and thought I'd try using Yosai instead of writing it myself. But I didn't see any how-tos on how to use it, especially regarding the details of hooking up an audit log, and also how to integrate with Flask.

cheers
adam

**Comment by Dowwie** [comment]
Did you visit the project web site, whose url is mentioned twice at the front of the Yosai github page?  

As for Flask integration -- if you're a subject matter expert of it then let's partner up and make it happen.  I'm working on the pyramid integration.
