### ISSUE TITLE
Flask Web Integration

### ISSUE THREAD

**Issue by surajsavita** [YosaiProject/yosai#17]
Thanks for such a wonderful framework.

I wanted to know if there is any flask integration documentation available.
Or if you can point me to the right direction that'll be of great help.

Cheers.

**Comment by Dowwie** [comment]
Hey Suraj!  You are very welcome.

There isn't a Flask integration yet. This can be *your* moment of glory if you are ready for it.  

Creating a flask_yosai integration ought to be a very straight-forward exercise.  If you know Flask, you could have a complete solution, with tests AND a blog post in **one day** of effort.

1. Write a FlaskWebRegistry class that subclasses yosai.web.web_abcs.WebRegistry
    -- A viable example is the one I created for Pyramid:  https://github.com/YosaiProject/pyramid_yosai/blob/master/pyramid_yosai/webregistry.py
    -- yosai web documentation:  https://yosaiproject.github.io/yosai/web
2. Write the flask-specific hooks (blueprint?) that let you import and use a flask_yosai integration in flask applications

3. Profit.


Feel free to email me at dkcdkg at google
