### ISSUE TITLE
Log in with Token

### ISSUE THREAD

**Issue by Woolworths** [YosaiProject/yosai#5]
UsernamePasswordToken requires you to give a username and password, but what if you want to log in with email and password?

**Comment by Dowwie** [comment]
good point -- kindly submit a PR, changing "username" references to "Identifier", update the affected tests and I'll approve

**Comment by Woolworths** [comment]
I was thinking something along the lines of xxToken (replace xx with something) and have identifier and password. I'll see what I can come up with.

**Comment by Dowwie** [comment]
that is what I meant -- IdentiferToken 

thoughts?

**Comment by Dowwie** [comment]
as this isn't an issue I'm closing it
