### ISSUE TITLE
Version Clarification

### ISSUE THREAD

**Issue by datamafia** [YosaiProject/yosai#9]
Hello, 

I finally have the time needed to get into Yosai and advance a project. I am getting pip errors (this should be familiar to many):

```error: command '/usr/bin/clang' failed with exit status 1```

Usually this is an OSX command line tool error. Not this time. It looks like a product of ```python-rapidjson``` requirement (https://github.com/YosaiProject/yosai/blob/master/setup.py#L38). 

Visiting https://pypi.python.org/pypi/python-rapidjson/ they state:

> We do not support legacy python versions, you will need to upgrade to Python 3 to use this library.

So Yosai is Python3 only? I am 2.7, I can go 3.x, but I was not planning on doing a full 3.x move until ~2020.

There could be other dependency issues, the aforementioned requirement was the first clear roadblock I ran into.

I am going to set up a 3.x env and see what happens. Thanks in advance, I will always accept user error as a valid answer.

**Comment by datamafia** [comment]
Update: Py3 allowed an error free install. Is there a Py3 requirement I missed skimming the dox?

**Comment by Dowwie** [comment]
correct -- py3 support only

**Comment by datamafia** [comment]
Well that kills a lot of Django users, also Flask. So, about 1/2 the web framework use. Bummer, big time. Is there a note in the dox I missed?

**Comment by Dowwie** [comment]
Yeah, I saw a lot of hands raised among the audience of thousands of people in PyCon Montreal last year when Guido asked who still uses py2.7 in production.

I've since updated the README to make the py3 requirement more clear.

I'm sorry to hear that this is presenting challenges for you.  I was looking forward to working together.

**Comment by datamafia** [comment]
No problem. Needed a reason to use Py3 more as there are very few in my world. 2.7 is not going away and ~2020 is when Django will be making it a requirement finally. Flask, well -- I don't think Armin will ever bump that framework over.  I just swapped out a new venv for my Django app. Closing out, see you soon. #thx
